### ISSUE TITLE
调用 Attr 报错，newXMLElement 方法未对 el 赋值

### ISSUE THREAD

**Issue by onlywsx** [nange/gospider#38]
func newXMLElement(el *colly.XMLElement, ctx *Context) *XMLElement {
	return &XMLElement{
		Name:     el.Name,
		Text:     el.Text,
		Request:  newRequest(el.Request, ctx),
		Response: newResponse(el.Response, ctx),
		DOM:      el.DOM,
		el:       el,
	}
}

func (x *XMLElement) Attr(k string) string {
	return x.el.Attr(k)
}

**Comment by nange** [comment]
thanks, fixed.
