### ISSUE TITLE
有计划开发使用js动态编写规则的功能吗

### ISSUE THREAD

**Issue by lchjczw** [nange/gospider#42]
有计划开发使用js动态编写规则的功能吗

**Comment by nange** [comment]
@lchjczw 
有计划支持调用chrome和页面进行交互，是基于[chromedp](https://github.com/chromedp/chromedp)来实现，目前chromedp还有些问题，需要等待其v2版本。 
js编写规则的功能目前还没有计划，不过如果有人愿意来实现，我持开放态度。
