### ISSUE TITLE
老兄，能否提供 windows的环境部署呢

### ISSUE THREAD

**Issue by ThunderLT** [nange/gospider#56]

**Comment by nange** [comment]
应该是可以在Windows上安装部署的，你遇到啥问题了吗

**Comment by nange** [comment]
https://github.com/nange/gospider/wiki/Install

**Comment by nange** [comment]
@ThunderLT 有遇到问题的话，就提出来哈。我也没怎么在windows上测试。

**Comment by ThunderLT** [comment]
@nange 确实有点问题，后来我还是用自己的轮子写了，有时间花点功夫看下，到时候给你提

**Comment by nange** [comment]
ok
