### ISSUE TITLE
cannot find package "github.com/appleboy/gin-jwt/v2

### ISSUE THREAD

**Issue by ThunderLT** [nange/gospider#57]
`cannot find package "github.com/appleboy/gin-jwt/v2'
没有我去这个包的地址看了下，好像没有v2路径，而且我把v2路径去掉以后直接编译也出问题了，是不是原作者给删了，大佬有没有备份

**Comment by nange** [comment]
![image](https://user-images.githubusercontent.com/2505751/61506175-d7046200-aa13-11e9-8c76-f15d5b3aa77f.png)

有v2呢。 你启用了GO111MODULE环境变了了么？ @ThunderLT

**Comment by nange** [comment]
```
export GO111MODULE=on
go build
``` 
这样应该就没问题了。包管理必须用go module的。

**Comment by ThunderLT** [comment]
ok,谢谢了，我确实去掉了GO MOD环境，刚刚编过了，好像GO MOD要求包的版本，我这里本地有包，但是GO MOD一直报错说我这里的包 UnRecongnied 所以，我把GO MOD都给删了，然后刚刚我去apple boy的issue区看了一下，直接把v2去掉，编译报错，最后把他的代码改了一下通过了

**Comment by nange** [comment]
@ThunderLT 你的go版本是多少，推荐最新的go 1.12版本。 然后不要把项目放在gopath下，放在另外的开发目录。 执行go build 会自动下载相应版本。 ps：需要科学上网或者设置```export GOPROXY=https://goproxy.io```
如果你还是用的老的基于gopath的build模式，肯定会报UnRecongnied的。

**Comment by ThunderLT** [comment]
@nange 太谢谢了，设置GOPROXY很有效！

**Comment by ThunderLT** [comment]
@我把issue可以关掉了，已解决！
