### ISSUE TITLE
百度新闻的example运行完成但是MYSQL里面的export表都是空的

### ISSUE THREAD

**Issue by ThunderLT** [nange/gospider#60]

**Comment by ThunderLT** [comment]
明明已经改了配置，仍然用admin去访问我的MYSQL，这肯定有问题啊

**Comment by ThunderLT** [comment]
>想知道哪里可以更改访问数据库的用户和密码

**Comment by nange** [comment]
方便的话，可以加微信详聊。 id:nange880820

**Comment by nange** [comment]
你是不是没有创建导出数据库？ 然后在创建任务页面选择对应数据库。

**Comment by ThunderLT** [comment]
@nange 导出数据库的账号密码没填对，用的默认的，我以为只要在环境变量里设置好了就ok了

**Comment by ThunderLT** [comment]
@nange 加你了大佬
